In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [7]:
arr2 = np.arange(10).reshape(2, 5)

In [9]:
np.cumsum(arr2)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [10]:
arr = np.random.randint(0, 1000, 1000000)
df = pd.DataFrame(arr)
df.head()

0
0  757
1  564
2  563
3  296
4   64

In [17]:
df.sum()

0    499090787
dtype: int64

In [20]:
%timeit max(df[0])

119 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit df.max()

2.04 ms ± 67.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit sum(arr)

90.6 ms ± 401 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit arr.sum()

538 µs ± 9.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
df = pd.DataFrame(np.random.random(size=(5, 3)), columns=list('ABC'))
df

A         B         C
0  0.909918  0.476746  0.412136
1  0.307706  0.689501  0.036212
2  0.293463  0.817175  0.003956
3  0.568507  0.772181  0.741288
4  0.145785  0.420930  0.196247

In [18]:
df.sum(axis=1)

0    1.798800
1    1.033419
2    1.114594
3    2.081977
4    0.762962
dtype: float64

In [20]:
df.min(axis=1)

0    0.412136
1    0.036212
2    0.003956
3    0.568507
4    0.145785
dtype: float64

In [26]:
df['D'] = 5

In [27]:
df

A         B         C  D
0  0.909918  0.476746  0.412136  5
1  0.307706  0.689501  0.036212  5
2  0.293463  0.817175  0.003956  5
3  0.568507  0.772181  0.741288  5
4  0.145785  0.420930  0.196247  5

In [37]:
df = pd.DataFrame(
        np.random.randn(3, 2), 
        columns=['foo', 'bar'], 
        index=['a', 'b', 'c'])
df

foo       bar
a -0.922288  0.017413
b -0.527411  1.605322
c -0.233553  2.215226

In [31]:
df.loc['b', 'foo'] = np.nan
df.loc['a', 'bar'] = np.nan
df

foo       bar
a  1.160275       NaN
b       NaN  0.447687
c  0.512915  0.433254

In [35]:
df[df.foo.isnull()]

foo       bar
b  NaN  0.447687

In [39]:
pd.Series({
        ('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102})

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [50]:
from sklearn.datasets import load_wine
# data = datasets.load_wine()
# df = pd.DataFrame(data.data, columns=data.feature_names)
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [18]:
df.shape, df.notna().shape  # размеры одинаковые - нуль значений нет

((178, 13), (178, 13))

In [19]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [46]:
diff_corr_table = df.corr(method='spearman') - df.corr()
diff_corr_table[(diff_corr_table > 0.08)|(diff_corr_table < -0.08)]

alcohol  malic_acid  ash  alcalinity_of_ash  \
alcohol                            NaN         NaN  NaN                NaN   
malic_acid                         NaN         NaN  NaN                NaN   
ash                                NaN         NaN  NaN                NaN   
alcalinity_of_ash                  NaN         NaN  NaN                NaN   
magnesium                     0.094705    0.134763  NaN          -0.086225   
total_phenols                      NaN         NaN  NaN                NaN   
flavanoids                         NaN    0.085804  NaN          -0.092400   
nonflavanoid_phenols               NaN         NaN  NaN                NaN   
proanthocyanins                    NaN         NaN  NaN                NaN   
color_intensity               0.089060         NaN  NaN          -0.092508   
hue                                NaN         NaN  NaN                NaN   
od280/od315_of_diluted_wines       NaN    0.113525  NaN                NaN   
proline                            NaN    0.134544  NaN                NaN   

                              magnesium  total_phenols  flavanoids  \
alcohol                        0.094705            NaN         NaN   
malic_acid                     0.134763            NaN    0.085804   
ash                                 NaN            NaN         NaN   
alcalinity_of_ash             -0.086225            NaN   -0.092400   
magnesium                           NaN            NaN         NaN   
total_phenols                       NaN            NaN         NaN   
flavanoids                          NaN            NaN         NaN   
nonflavanoid_phenols                NaN            NaN         NaN   
proanthocyanins                     NaN            NaN         NaN   
color_intensity                0.157079            NaN    0.129469   
hue                                 NaN            NaN         NaN   
od280/od315_of_diluted_wines        NaN            NaN         NaN   
proline                        0.114224            NaN         NaN   

                              nonflavanoid_phenols  proanthocyanins  \
alcohol                                        NaN              NaN   
malic_acid                                     NaN              NaN   
ash                                            NaN              NaN   
alcalinity_of_ash                              NaN              NaN   
magnesium                                      NaN              NaN   
total_phenols                                  NaN              NaN   
flavanoids                                     NaN              NaN   
nonflavanoid_phenols                           NaN              NaN   
proanthocyanins                                NaN              NaN   
color_intensity                                NaN              NaN   
hue                                            NaN              NaN   
od280/od315_of_diluted_wines                   NaN              NaN   
proline                                        NaN              NaN   

                              color_intensity       hue  \
alcohol                              0.089060       NaN   
malic_acid                                NaN       NaN   
ash                                       NaN       NaN   
alcalinity_of_ash                   -0.092508       NaN   
magnesium                            0.157079       NaN   
total_phenols                             NaN       NaN   
flavanoids                           0.129469       NaN   
nonflavanoid_phenols                      NaN       NaN   
proanthocyanins                           NaN       NaN   
color_intensity                           NaN  0.103291   
hue                                  0.103291       NaN   
od280/od315_of_diluted_wines         0.111299 -0.080014   
proline                              0.140996       NaN   

                              od280/od315_of_diluted_wines   proline  
alcohol                                                NaN      

In [51]:
df[(df > 10)|(df < -10)]

alcohol  malic_acid  ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23         NaN  NaN               15.6      127.0            NaN   
1      13.20         NaN  NaN               11.2      100.0            NaN   
2      13.16         NaN  NaN               18.6      101.0            NaN   
3      14.37         NaN  NaN               16.8      113.0            NaN   
4      13.24         NaN  NaN               21.0      118.0            NaN   
..       ...         ...  ...                ...        ...            ...   
173    13.71         NaN  NaN               20.5       95.0            NaN   
174    13.40         NaN  NaN               23.0      102.0            NaN   
175    13.27         NaN  NaN               20.0      120.0            NaN   
176    13.17         NaN  NaN               20.0      120.0            NaN   
177    14.13         NaN  NaN               24.5       96.0            NaN   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity  hue  \
0           NaN                   NaN              NaN              NaN  NaN   
1           NaN                   NaN              NaN              NaN  NaN   
2           NaN                   NaN              NaN              NaN  NaN   
3           NaN                   NaN              NaN              NaN  NaN   
4           NaN                   NaN              NaN              NaN  NaN   
..          ...                   ...              ...              ...  ...   
173         NaN                   NaN              NaN              NaN  NaN   
174         NaN                   NaN              NaN              NaN  NaN   
175         NaN                   NaN              NaN             10.2  NaN   
176         NaN                   NaN              NaN              NaN  NaN   
177         NaN                   NaN              NaN              NaN  NaN   

     od280/od315_of_diluted_wines  proline  
0                             NaN   1065.0  
1                             NaN   1050.0  
2                             NaN   1185.0  
3                             NaN   1480.0  
4                             NaN    735.0  
..                            ...      ...  
173                           NaN    740.0  
174                           NaN    750.0  
175                           NaN    835.0  
176                           NaN    840.0  
177                           NaN    560.0  

[178 rows x 13 columns]