In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [7]:
arr2 = np.arange(10).reshape(2, 5)

In [9]:
np.cumsum(arr2)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [10]:
arr = np.random.randint(0, 1000, 1000000)
df = pd.DataFrame(arr)
df.head()

0
0  757
1  564
2  563
3  296
4   64

In [17]:
df.sum()

0    499090787
dtype: int64

In [20]:
%timeit max(df[0])

119 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit df.max()

2.04 ms ± 67.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit sum(arr)

90.6 ms ± 401 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit arr.sum()

538 µs ± 9.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
