In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [7]:
arr2 = np.arange(10).reshape(2, 5)

In [9]:
np.cumsum(arr2)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)